export const SCHOOL_LIST_LIST = 'CATEGORY_LIST'
export const SCHOOL_LIST_ADD = 'CATEGORY_ADD'
export const SCHOOL_LIST_UPDATE = 'CATEGORY_UPDATE'
export const SCHOOL_LIST_REMOVE = 'CATEGORY_REMOVE'
export const SPINNER_ADD = 'SPINNER_ADD'
export const SPINNER_REMOVE = 'SPINNER_REMOVE'
 export default {
  SCHOOL_LIST_LIST,
  SCHOOL_LIST_ADD,
  SCHOOL_LIST_UPDATE,
  SCHOOL_LIST_REMOVE,
  SPINNER_REMOVE ,

};