export const CATEGORY_LIST = 'CATEGORY_LIST'
export const CATEGORY_ADD = 'CATEGORY_ADD'
export const CATEGORY_UPDATE = 'CATEGORY_UPDATE'
export const CATEGORY_REMOVE = 'CATEGORY_REMOVE'
export const SPINNER_ADD = 'SPINNER_ADD'
export const SPINNER_REMOVE = 'SPINNER_REMOVE'
 export default {
  CATEGORY_LIST,
  CATEGORY_ADD,
  CATEGORY_UPDATE,
  CATEGORY_REMOVE,
  SPINNER_REMOVE ,

};