export const COURSE_LIST = 'COURSE_LIST'
export const COURSE_ADD = 'COURSE_ADD'
export const COURSE_UPDATE = 'COURSE_UPDATE'
export const COURSE_REMOVE = 'COURSE_REMOVE'
export const CATEGORY_LIST = 'CATEGORY_LIST';
export const SPINNER_ADD = 'SPINNER_ADD'
export default {
  COURSE_LIST,
  COURSE_ADD,
  COURSE_UPDATE,
  COURSE_REMOVE,
  CATEGORY_LIST,
  SPINNER_ADD,
};