export const ASSIGN_COURSE_LIST = 'CATEGORY_LIST'
export const ASSIGN_COURSE_ADD = 'CATEGORY_ADD'
export const ASSIGN_COURSE_UPDATE = 'CATEGORY_UPDATE'
export const ASSIGN_COURSE_REMOVE = 'CATEGORY_REMOVE'
export const SPINNER_ADD = 'SPINNER_ADD'
export const SPINNER_REMOVE = 'SPINNER_REMOVE'
export const COURSE_SCHOOL_LIST = 'COURSE_SCHOOL_LIST'
 export default {
  ASSIGN_COURSE_LIST,
  ASSIGN_COURSE_ADD,
  ASSIGN_COURSE_UPDATE,
  ASSIGN_COURSE_REMOVE,
  SPINNER_REMOVE ,
  COURSE_SCHOOL_LIST,

};