export const PROJECT_ADMIN_LIST = 'PROJECT_ADMIN_LIST'
export const PROJECT_ADMIN_ADD = 'PROJECT_ADMIN_ADD'
export const PROJECT_ADMIN_UPDATE = 'PROJECT_ADMIN_UPDATE'
export const PROJECT_ADMIN_REMOVE = 'PROJECT_ADMIN_REMOVE'
export const SPINNER_ADD = 'SPINNER_ADD'
export const SPINNER_REMOVE = 'SPINNER_REMOVE'
 export default {
  PROJECT_ADMIN_LIST,
  PROJECT_ADMIN_ADD,
  PROJECT_ADMIN_UPDATE,
  PROJECT_ADMIN_REMOVE,
  SPINNER_ADD,

};